/* Generated By:JavaCC: Do not edit this line. MainConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MainConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PREGUNTAR = 1;
  /** RegularExpression Id. */
  int SINO = 2;
  /** RegularExpression Id. */
  int HACER = 3;
  /** RegularExpression Id. */
  int CICLO = 4;
  /** RegularExpression Id. */
  int CICLO_HASTA = 5;
  /** RegularExpression Id. */
  int FUNCION = 6;
  /** RegularExpression Id. */
  int REGRESAR = 7;
  /** RegularExpression Id. */
  int CLASE = 8;
  /** RegularExpression Id. */
  int HERENCIA = 9;
  /** RegularExpression Id. */
  int INTERFAZ = 10;
  /** RegularExpression Id. */
  int IMPLEMENTA = 11;
  /** RegularExpression Id. */
  int ESTRUCTURA = 12;
  /** RegularExpression Id. */
  int IMPORTAR = 13;
  /** RegularExpression Id. */
  int EXPORTAR = 14;
  /** RegularExpression Id. */
  int USAR = 15;
  /** RegularExpression Id. */
  int ORIGEN = 16;
  /** RegularExpression Id. */
  int MODULO = 17;
  /** RegularExpression Id. */
  int TAMAÑO_DE = 18;
  /** RegularExpression Id. */
  int ALINEAMIENTO_DE = 19;
  /** RegularExpression Id. */
  int INSEGURO = 20;
  /** RegularExpression Id. */
  int IMPRIMIR = 21;
  /** RegularExpression Id. */
  int ARITMETICA = 22;
  /** RegularExpression Id. */
  int UNARIOS = 23;
  /** RegularExpression Id. */
  int ASIGNACION = 24;
  /** RegularExpression Id. */
  int COMPARACION = 25;
  /** RegularExpression Id. */
  int LOGICOS = 26;
  /** RegularExpression Id. */
  int BITWISE = 27;
  /** RegularExpression Id. */
  int ASIGNACION_COMPUESTA = 28;
  /** RegularExpression Id. */
  int OPERADOR_TRES_VIAS = 29;
  /** RegularExpression Id. */
  int OPERADOR_COALESCENCIA = 30;
  /** RegularExpression Id. */
  int OPERADOR_SEGURO = 31;
  /** RegularExpression Id. */
  int OPERADOR_TERNARIO = 32;
  /** RegularExpression Id. */
  int OPERADOR_ENCADENADOR = 33;
  /** RegularExpression Id. */
  int FLECHA = 34;
  /** RegularExpression Id. */
  int RESOLUCION_AMBITO = 35;
  /** RegularExpression Id. */
  int SPREAD = 36;
  /** RegularExpression Id. */
  int RANGO = 37;
  /** RegularExpression Id. */
  int DATO_DINAMICO = 38;
  /** RegularExpression Id. */
  int DATO_CADENA = 39;
  /** RegularExpression Id. */
  int DATO_CARACTER = 40;
  /** RegularExpression Id. */
  int DATO_BYTE = 41;
  /** RegularExpression Id. */
  int DATO_DECIMAL = 42;
  /** RegularExpression Id. */
  int DATO_ESTATICO = 43;
  /** RegularExpression Id. */
  int DATO_COMPLEJO = 44;
  /** RegularExpression Id. */
  int DATO_BINARIO = 45;
  /** RegularExpression Id. */
  int CONSTANTE = 46;
  /** RegularExpression Id. */
  int MODIFICADOR = 47;
  /** RegularExpression Id. */
  int DATO_VACIO = 48;
  /** RegularExpression Id. */
  int PROCEDIMIENTO = 49;
  /** RegularExpression Id. */
  int BANDERA = 50;
  /** RegularExpression Id. */
  int NUEVO = 51;
  /** RegularExpression Id. */
  int ACCESO = 52;
  /** RegularExpression Id. */
  int PAQUETE = 53;
  /** RegularExpression Id. */
  int TIPO_INSTANCIA = 54;
  /** RegularExpression Id. */
  int TIPO_DATO = 55;
  /** RegularExpression Id. */
  int TIPO_FUNCION = 56;
  /** RegularExpression Id. */
  int TIPO_PROPIO = 57;
  /** RegularExpression Id. */
  int VECTOR = 58;
  /** RegularExpression Id. */
  int DATO_ENTERO_SIN_SIGNO = 59;
  /** RegularExpression Id. */
  int DATO_COLECCION = 60;
  /** RegularExpression Id. */
  int INTENTA = 61;
  /** RegularExpression Id. */
  int ATRAPA = 62;
  /** RegularExpression Id. */
  int FINAL = 63;
  /** RegularExpression Id. */
  int LANZA = 64;
  /** RegularExpression Id. */
  int PANICO = 65;
  /** RegularExpression Id. */
  int ELIGE = 66;
  /** RegularExpression Id. */
  int CASO = 67;
  /** RegularExpression Id. */
  int POR_DEFECTO = 68;
  /** RegularExpression Id. */
  int COINCIDE = 69;
  /** RegularExpression Id. */
  int CONTINUAR = 70;
  /** RegularExpression Id. */
  int DETENER = 71;
  /** RegularExpression Id. */
  int VE_A = 72;
  /** RegularExpression Id. */
  int EN = 73;
  /** RegularExpression Id. */
  int SINCRONIZADO = 74;
  /** RegularExpression Id. */
  int ASINCRONICO = 75;
  /** RegularExpression Id. */
  int ESPERA = 76;
  /** RegularExpression Id. */
  int EXPLICITO = 77;
  /** RegularExpression Id. */
  int OPERADOR = 78;
  /** RegularExpression Id. */
  int COMO = 79;
  /** RegularExpression Id. */
  int ES = 80;
  /** RegularExpression Id. */
  int CONVERSION_DINAMICA = 81;
  /** RegularExpression Id. */
  int CONVERSION_ESTATICA = 82;
  /** RegularExpression Id. */
  int PLANTILLA = 83;
  /** RegularExpression Id. */
  int TIPO_PLANTILLA = 84;
  /** RegularExpression Id. */
  int REQUERIMIENTOS = 85;
  /** RegularExpression Id. */
  int CONCEPTO = 86;
  /** RegularExpression Id. */
  int TIPO_VARIABLE = 87;
  /** RegularExpression Id. */
  int REFERENCIA = 88;
  /** RegularExpression Id. */
  int SALIDA = 89;
  /** RegularExpression Id. */
  int MOVER = 90;
  /** RegularExpression Id. */
  int PRESTAMO = 91;
  /** RegularExpression Id. */
  int TIEMPO_VIDA = 92;
  /** RegularExpression Id. */
  int ASIGNAR_MONTICULO = 93;
  /** RegularExpression Id. */
  int FIJAR_MEMORIA = 94;
  /** RegularExpression Id. */
  int ASIGNAR_STACK = 95;
  /** RegularExpression Id. */
  int HILO_LOCAL = 96;
  /** RegularExpression Id. */
  int DUERME = 97;
  /** RegularExpression Id. */
  int TIEMPO_ESPERA = 98;
  /** RegularExpression Id. */
  int APARECER = 99;
  /** RegularExpression Id. */
  int EVENTO = 100;
  /** RegularExpression Id. */
  int AGREGAR_EVENTO = 101;
  /** RegularExpression Id. */
  int REMOVER_EVENTO = 102;
  /** RegularExpression Id. */
  int DELEGADO = 103;
  /** RegularExpression Id. */
  int VALOR = 104;
  /** RegularExpression Id. */
  int OBTENER = 105;
  /** RegularExpression Id. */
  int ESTABLECER = 106;
  /** RegularExpression Id. */
  int COVARIANZA = 107;
  /** RegularExpression Id. */
  int CONTRAVARIANZA = 108;
  /** RegularExpression Id. */
  int SELECCIONAR = 109;
  /** RegularExpression Id. */
  int DONDE = 110;
  /** RegularExpression Id. */
  int AGRUPAR_POR = 111;
  /** RegularExpression Id. */
  int ORDENAR_POR = 112;
  /** RegularExpression Id. */
  int ASCENDENTE = 113;
  /** RegularExpression Id. */
  int DESCENDENTE = 114;
  /** RegularExpression Id. */
  int INSERTAR = 115;
  /** RegularExpression Id. */
  int ACTUALIZAR = 116;
  /** RegularExpression Id. */
  int ELIMINAR = 117;
  /** RegularExpression Id. */
  int TENIENDO = 118;
  /** RegularExpression Id. */
  int UNION = 119;
  /** RegularExpression Id. */
  int INTERNA = 120;
  /** RegularExpression Id. */
  int EXTERNA = 121;
  /** RegularExpression Id. */
  int IZQUIERDA = 122;
  /** RegularExpression Id. */
  int DERECHA = 123;
  /** RegularExpression Id. */
  int CRUZADA = 124;
  /** RegularExpression Id. */
  int NATURAL = 125;
  /** RegularExpression Id. */
  int UNION_RESULTADOS = 126;
  /** RegularExpression Id. */
  int INTERSECCION = 127;
  /** RegularExpression Id. */
  int EXCEPTO = 128;
  /** RegularExpression Id. */
  int DISTINTO = 129;
  /** RegularExpression Id. */
  int TODOS = 130;
  /** RegularExpression Id. */
  int CUALQUIER = 131;
  /** RegularExpression Id. */
  int ALGUN = 132;
  /** RegularExpression Id. */
  int EXISTE = 133;
  /** RegularExpression Id. */
  int ENTRE = 134;
  /** RegularExpression Id. */
  int COMO_SQL = 135;
  /** RegularExpression Id. */
  int PRIMARIO = 136;
  /** RegularExpression Id. */
  int FORANEO = 137;
  /** RegularExpression Id. */
  int REFERENCIAS = 138;
  /** RegularExpression Id. */
  int RESTRICCION = 139;
  /** RegularExpression Id. */
  int BD = 140;
  /** RegularExpression Id. */
  int TABLA = 141;
  /** RegularExpression Id. */
  int COLUMNA = 142;
  /** RegularExpression Id. */
  int FILA = 143;
  /** RegularExpression Id. */
  int ESQUEMA = 144;
  /** RegularExpression Id. */
  int VISTA = 145;
  /** RegularExpression Id. */
  int INDICE = 146;
  /** RegularExpression Id. */
  int DISPARADOR = 147;
  /** RegularExpression Id. */
  int TRANSACCIONES = 148;
  /** RegularExpression Id. */
  int MENSAJE = 149;
  /** RegularExpression Id. */
  int REVERTIR = 150;
  /** RegularExpression Id. */
  int CONCEDER = 151;
  /** RegularExpression Id. */
  int REVOCAR = 152;
  /** RegularExpression Id. */
  int ALTERAR = 153;
  /** RegularExpression Id. */
  int BORRAR = 154;
  /** RegularExpression Id. */
  int MACRO = 155;
  /** RegularExpression Id. */
  int IMPRIMIR_MACRO = 156;
  /** RegularExpression Id. */
  int VECTOR_MACRO = 157;
  /** RegularExpression Id. */
  int ASERCION_MACRO = 158;
  /** RegularExpression Id. */
  int SELECCIONAR_MACRO = 159;
  /** RegularExpression Id. */
  int OPCIONAL = 160;
  /** RegularExpression Id. */
  int PRESENTE = 161;
  /** RegularExpression Id. */
  int RESULTADO = 162;
  /** RegularExpression Id. */
  int EXITOSO = 163;
  /** RegularExpression Id. */
  int ERROR = 164;
  /** RegularExpression Id. */
  int ITERADOR = 165;
  /** RegularExpression Id. */
  int CLONAR = 166;
  /** RegularExpression Id. */
  int COPIAR = 167;
  /** RegularExpression Id. */
  int HASH = 168;
  /** RegularExpression Id. */
  int CONTADOR_REFERENCIAS = 169;
  /** RegularExpression Id. */
  int EXCLUSION_MUTUA = 170;
  /** RegularExpression Id. */
  int CANAL = 171;
  /** RegularExpression Id. */
  int REMITENTE = 172;
  /** RegularExpression Id. */
  int RECEPTOR = 173;
  /** RegularExpression Id. */
  int SERIALIZACION = 174;
  /** RegularExpression Id. */
  int PASAR = 175;
  /** RegularExpression Id. */
  int CON = 176;
  /** RegularExpression Id. */
  int NO_LOCAL = 177;
  /** RegularExpression Id. */
  int APLAZA = 178;
  /** RegularExpression Id. */
  int SIGUIENTE_CASO = 179;
  /** RegularExpression Id. */
  int GUARDIA = 180;
  /** RegularExpression Id. */
  int A_MENOS_QUE = 181;
  /** RegularExpression Id. */
  int HASTA = 182;
  /** RegularExpression Id. */
  int REPITE = 183;
  /** RegularExpression Id. */
  int SIGUIENTE = 184;
  /** RegularExpression Id. */
  int CALCULO_FLOTANTE_ESTRICTO = 185;
  /** RegularExpression Id. */
  int TRANSITORIO = 186;
  /** RegularExpression Id. */
  int NATIVO = 187;
  /** RegularExpression Id. */
  int ACTUAL = 188;
  /** RegularExpression Id. */
  int COMPROBADO = 189;
  /** RegularExpression Id. */
  int SIN_COMPROBAR = 190;
  /** RegularExpression Id. */
  int BLOQUEO = 191;
  /** RegularExpression Id. */
  int PARAMETROS = 192;
  /** RegularExpression Id. */
  int ARCHIVO = 193;
  /** RegularExpression Id. */
  int AMIGO = 194;
  /** RegularExpression Id. */
  int VIRTUAL = 195;
  /** RegularExpression Id. */
  int SOBRE_ESCRIBE = 196;
  /** RegularExpression Id. */
  int DERIVAR = 197;
  /** RegularExpression Id. */
  int HILO = 198;
  /** RegularExpression Id. */
  int CORRUTINA = 199;
  /** RegularExpression Id. */
  int FUTURO = 200;
  /** RegularExpression Id. */
  int PROMESA = 201;
  /** RegularExpression Id. */
  int PARALELO = 202;
  /** RegularExpression Id. */
  int SECUENCIAL = 203;
  /** RegularExpression Id. */
  int CRITICO = 204;
  /** RegularExpression Id. */
  int BARRERA = 205;
  /** RegularExpression Id. */
  int SEMAFORO = 206;
  /** RegularExpression Id. */
  int ASEGURA = 207;
  /** RegularExpression Id. */
  int MEMORIA = 208;
  /** RegularExpression Id. */
  int EN_LINEA = 209;
  /** RegularExpression Id. */
  int SALTO = 210;
  /** RegularExpression Id. */
  int FORMATO_JSON = 211;
  /** RegularExpression Id. */
  int FORMATO_XML = 212;
  /** RegularExpression Id. */
  int FORMATO_TXT = 213;
  /** RegularExpression Id. */
  int FORMATO_SQL = 214;
  /** RegularExpression Id. */
  int PAREN_IZQ = 215;
  /** RegularExpression Id. */
  int PAREN_DER = 216;
  /** RegularExpression Id. */
  int LLAVE_IZQ = 217;
  /** RegularExpression Id. */
  int LLAVE_DER = 218;
  /** RegularExpression Id. */
  int CORCHETE_IZQ = 219;
  /** RegularExpression Id. */
  int CORCHETE_DER = 220;
  /** RegularExpression Id. */
  int PUNTOCOMA = 221;
  /** RegularExpression Id. */
  int COMA = 222;
  /** RegularExpression Id. */
  int LETRA = 223;
  /** RegularExpression Id. */
  int DIGITO = 224;
  /** RegularExpression Id. */
  int GUION_BAJO = 225;
  /** RegularExpression Id. */
  int PUNTO = 226;
  /** RegularExpression Id. */
  int COMILLA_DOBLE = 227;
  /** RegularExpression Id. */
  int COMILLA_SIMPLE = 228;
  /** RegularExpression Id. */
  int BARRA_INVERTIDA = 229;
  /** RegularExpression Id. */
  int ESPACIO_BLANCO = 230;
  /** RegularExpression Id. */
  int TABULADOR = 231;
  /** RegularExpression Id. */
  int NUEVA_LINEA = 232;
  /** RegularExpression Id. */
  int RETORNO_CARRO = 233;
  /** RegularExpression Id. */
  int CUERPO_COMENTARIO = 234;
  /** RegularExpression Id. */
  int VARIABLE = 235;
  /** RegularExpression Id. */
  int ENTERO = 236;
  /** RegularExpression Id. */
  int DECIMAL = 237;
  /** RegularExpression Id. */
  int CADENA_DOBLE = 238;
  /** RegularExpression Id. */
  int CADENA_SIMPLE = 239;
  /** RegularExpression Id. */
  int COMENTARIO_LINEA = 240;
  /** RegularExpression Id. */
  int ESPACIO = 241;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"if\"",
    "\"else\"",
    "\"do\"",
    "<CICLO>",
    "\"for\"",
    "<FUNCION>",
    "<REGRESAR>",
    "\"class\"",
    "\"extends\"",
    "<INTERFAZ>",
    "<IMPLEMENTA>",
    "\"struct\"",
    "<IMPORTAR>",
    "\"export\"",
    "<USAR>",
    "\"from\"",
    "\"mod\"",
    "\"sizeof\"",
    "\"alignof\"",
    "\"unsafe\"",
    "<IMPRIMIR>",
    "<ARITMETICA>",
    "<UNARIOS>",
    "<ASIGNACION>",
    "<COMPARACION>",
    "<LOGICOS>",
    "<BITWISE>",
    "<ASIGNACION_COMPUESTA>",
    "\"<=>\"",
    "\"??\"",
    "\"?\"",
    "\"?:\"",
    "\"|>\"",
    "<FLECHA>",
    "\"::\"",
    "\"...\"",
    "<RANGO>",
    "<DATO_DINAMICO>",
    "\"string\"",
    "\"char\"",
    "\"byte\"",
    "<DATO_DECIMAL>",
    "<DATO_ESTATICO>",
    "\"complex\"",
    "\"boolean\"",
    "\"const\"",
    "<MODIFICADOR>",
    "<DATO_VACIO>",
    "\"void\"",
    "<BANDERA>",
    "\"new\"",
    "<ACCESO>",
    "<PAQUETE>",
    "\"instanceof\"",
    "\"typeof\"",
    "\"typedef\"",
    "<TIPO_PROPIO>",
    "\"vector\"",
    "<DATO_ENTERO_SIN_SIGNO>",
    "<DATO_COLECCION>",
    "\"try\"",
    "\"catch\"",
    "\"finally\"",
    "<LANZA>",
    "\"panic!\"",
    "\"switch\"",
    "\"case\"",
    "\"default\"",
    "\"match\"",
    "\"continue\"",
    "\"break\"",
    "\"goto\"",
    "<EN>",
    "\"synchronized\"",
    "<ASINCRONICO>",
    "\"await\"",
    "\"explicit\"",
    "\"operator\"",
    "\"as\"",
    "\"is\"",
    "\"dynamic_cast\"",
    "\"static_cast\"",
    "\"template\"",
    "\"typename\"",
    "\"requires\"",
    "\"concept\"",
    "\"typevar\"",
    "\"ref\"",
    "\"out\"",
    "<MOVER>",
    "\"borrow\"",
    "\"lifetime\"",
    "\"box\"",
    "\"fixed\"",
    "\"stackalloc\"",
    "\"thread_local\"",
    "\"sleep\"",
    "\"timeout\"",
    "\"spawn\"",
    "\"event\"",
    "\"add\"",
    "\"remove\"",
    "\"delegate\"",
    "\"value\"",
    "\"get\"",
    "\"set\"",
    "\"covariant\"",
    "\"contravariant\"",
    "\"select\"",
    "\"where\"",
    "\"group by\"",
    "\"order by\"",
    "\"ascending\"",
    "\"descending\"",
    "\"insert\"",
    "\"update\"",
    "\"delete\"",
    "\"having\"",
    "\"join\"",
    "\"inner\"",
    "\"outer\"",
    "\"left\"",
    "\"right\"",
    "\"cross\"",
    "\"natural\"",
    "\"union\"",
    "\"intersect\"",
    "\"except\"",
    "\"distinct\"",
    "\"all\"",
    "\"any\"",
    "\"some\"",
    "\"exists\"",
    "\"between\"",
    "\"like\"",
    "\"primary\"",
    "\"foreign\"",
    "\"references\"",
    "\"constraint\"",
    "\"database\"",
    "\"table\"",
    "\"column\"",
    "\"row\"",
    "\"schema\"",
    "\"view\"",
    "\"index\"",
    "\"trigger\"",
    "\"transaction\"",
    "\"commit\"",
    "\"rollback\"",
    "\"grant\"",
    "\"revoke\"",
    "\"alter\"",
    "\"drop\"",
    "\"macro\"",
    "\"println!\"",
    "\"vec!\"",
    "\"assert!\"",
    "\"select!\"",
    "\"Option\"",
    "\"Some\"",
    "\"Result\"",
    "\"Ok\"",
    "\"Err\"",
    "\"Iterator\"",
    "\"Clone\"",
    "\"Copy\"",
    "\"Hash\"",
    "\"Rc\"",
    "\"Mutex\"",
    "\"Channel\"",
    "\"Sender\"",
    "\"Receiver\"",
    "\"serde\"",
    "\"pass\"",
    "\"with\"",
    "\"nonlocal\"",
    "\"defer\"",
    "\"fallthrough\"",
    "\"guard\"",
    "\"unless\"",
    "\"until\"",
    "\"redo\"",
    "\"next\"",
    "\"strictfp\"",
    "\"transient\"",
    "\"native\"",
    "\"internal\"",
    "\"checked\"",
    "\"unchecked\"",
    "\"lock\"",
    "\"params\"",
    "\"file\"",
    "\"friend\"",
    "\"virtual\"",
    "\"override\"",
    "\"derive\"",
    "\"thread\"",
    "\"coroutine\"",
    "\"future\"",
    "\"promise\"",
    "\"parallel\"",
    "\"sequential\"",
    "\"critical\"",
    "\"barrier\"",
    "\"semaphore\"",
    "\"ensures\"",
    "\"memory\"",
    "\"inline\"",
    "\"jpm\"",
    "\"json\"",
    "\"xml\"",
    "\"txt\"",
    "\"sql\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "<LETRA>",
    "<DIGITO>",
    "\"_\"",
    "\".\"",
    "\"\\\"\"",
    "\"\\\'\"",
    "\"\\\\\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<CUERPO_COMENTARIO>",
    "<VARIABLE>",
    "<ENTERO>",
    "<DECIMAL>",
    "<CADENA_DOBLE>",
    "<CADENA_SIMPLE>",
    "<COMENTARIO_LINEA>",
    "<ESPACIO>",
  };

}
